sudo: required
dist: trusty

language: ruby
rvm:
    - 2.4

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules

before_install:
    - nvm use 8.9.1

before_script: "_ci/setup.sh"
script: "_ci/build.sh"
after_success: "_ci/deploy.sh"

notifications:
    email: false
