sudo: required
dist: trusty

language: ruby
rvm:
    - 2.4

cache:
  bundler: true
  directories:
  - "$TRAVIS_BUILD_DIR/node_modules"
  - "$HOME/google-cloud-sdk/"



before_install:
    - nvm install 9.5.0
    - nvm use 9.5.0
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    # Add gcloud to $PATH
    - source /home/travis/google-cloud-sdk/path.bash.inc
    - gcloud version

before_script: "_ci/setup.sh"
script: "_ci/build.sh"
after_success: "_ci/deploy.sh"

notifications:
    email: false
