# The Basics
# --------------------
title:          "HackCancer"
description:    "The crossroad event between Health and Data Science"
url:            "http://hackcancer.eu/"
analyticsID:    ""

# Form actions
forms:
    contact: 'https://formspree.io/hi@hackcancer.eu'
    newsletter: "https://iomed.us12.list-manage.com/subscribe/post?u=4d1374c88688ad88704c94eeb&amp;id=89074ad53e"

# Urls
# --------------------
permalink: pretty


# Generator
# --------------------
source:         ./_src
destination:    ./_dist


# Languages
# --------------------
languages: ["en", "es", "eu"]
default_lang: "es"
exclude_from_localization: ["assets"]
parallel_localization: true


# Plugins
# --------------------
plugins:
    - jekyll-polyglot
    - jekyll-sitemap
    - jekyll-redirect-from

exclude:
    - "README.md"
